export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const FILTER_ARTICLES_BY_SELECTION = 'FILTER_ARTICLES_BY_SELECTION'

export const FILTER_ARTICLES_BY_DATE = 'FILTER_ARTICLES_BY_DATE'